import "reflect-metadata";
import { DataSource } from "typeorm";
import { Institution } from "./src/entities/Institution";

// Create a DataSource specifically for seeding
const SeederDataSource = new DataSource({
  type: "postgres",
  url: process.env.DATABASE_URL,
  synchronize: true,
  logging: process.env.NODE_ENV === "development",
  entities: [Institution],
  ssl:
    process.env.NODE_ENV === "production"
      ? { rejectUnauthorized: false }
      : false,
});

const institutions = [
  // Federal Universities
  {
    name: "Abubakar Tafawa Balewa University",
    code: "ATBU",
    state: "Bauchi",
    city: "Bauchi",
    type: "University",
  },
  {
    name: "Ahmadu Bello University",
    code: "ABU",
    state: "Kaduna",
    city: "Zaria",
    type: "University",
  },
  {
    name: "Alex Ekwueme Federal University Ndufu Alike Ikwo",
    code: "AE-FUNAI",
    state: "Ebonyi",
    city: "Ikwo",
    type: "University",
  },
  {
    name: "Bayero University",
    code: "BUK",
    state: "Kano",
    city: "Kano",
    type: "University",
  },
  {
    name: "Federal University of Agriculture, Abeokuta",
    code: "FUNAAB",
    state: "Ogun",
    city: "Abeokuta",
    type: "University",
  },
  {
    name: "Federal University of Applied Sciences Kachia",
    code: "FUASK",
    state: "Kaduna",
    city: "Kachia",
    type: "University",
  },
  {
    name: "Federal University Birnin Kebbi",
    code: "FUBK",
    state: "Kebbi",
    city: "Birnin Kebbi",
    type: "University",
  },
  {
    name: "Federal University Dutse",
    code: "FUD",
    state: "Jigawa",
    city: "Dutse",
    type: "University",
  },
  {
    name: "Federal University Dutsin-Ma",
    code: "FUDM",
    state: "Katsina",
    city: "Dutsin-Ma",
    type: "University",
  },
  {
    name: "Federal University Gashua",
    code: "FUGASHUA",
    state: "Yobe",
    city: "Gashua",
    type: "University",
  },
  {
    name: "Federal University Gusau",
    code: "FUGUS",
    state: "Zamfara",
    city: "Gusau",
    type: "University",
  },
  {
    name: "Federal University Kashere",
    code: "FUK",
    state: "Gombe",
    city: "Kashere",
    type: "University",
  },
  {
    name: "Federal University Lokoja",
    code: "FUL",
    state: "Kogi",
    city: "Lokoja",
    type: "University",
  },
  {
    name: "Federal University of Lafia",
    code: "FULAFIA",
    state: "Nasarawa",
    city: "Lafia",
    type: "University",
  },
  {
    name: "Federal University of Petroleum Resources Effurun",
    code: "FUPRE",
    state: "Delta",
    city: "Effurun",
    type: "University",
  },
  {
    name: "Federal University of Technology Akure",
    code: "FUTA",
    state: "Ondo",
    city: "Akure",
    type: "University",
  },
  {
    name: "Federal University of Technology Minna",
    code: "FUTMIN",
    state: "Niger",
    city: "Minna",
    type: "University",
  },
  {
    name: "Federal University of Technology Owerri",
    code: "FUTO",
    state: "Imo",
    city: "Owerri",
    type: "University",
  },
  {
    name: "Federal University Otuoke",
    code: "FUO",
    state: "Bayelsa",
    city: "Otuoke",
    type: "University",
  },
  {
    name: "Federal University Oye-Ekiti",
    code: "FUOYE",
    state: "Ekiti",
    city: "Oye-Ekiti",
    type: "University",
  },
  {
    name: "Federal University Wukari",
    code: "FUW",
    state: "Taraba",
    city: "Wukari",
    type: "University",
  },
  {
    name: "Michael Okpara University of Agriculture, Umudike",
    code: "MOUAU",
    state: "Abia",
    city: "Umudike",
    type: "University",
  },
  {
    name: "Modibbo Adama University, Yola",
    code: "MAU",
    state: "Adamawa",
    city: "Yola",
    type: "University",
  },
  {
    name: "National Open University of Nigeria",
    code: "NOUN",
    state: "Lagos",
    city: "Victoria Island",
    type: "University",
  },
  {
    name: "Nnamdi Azikiwe University",
    code: "UNIZIK",
    state: "Anambra",
    city: "Awka",
    type: "University",
  },
  {
    name: "Obafemi Awolowo University",
    code: "OAU",
    state: "Osun",
    city: "Ile Ife",
    type: "University",
  },
  {
    name: "University of Abuja",
    code: "UNIABUJA",
    state: "Federal Capital Territory",
    city: "Gwagwalada",
    type: "University",
  },
  {
    name: "University of Agriculture, Makurdi",
    code: "UAM",
    state: "Benue",
    city: "Makurdi",
    type: "University",
  },
  {
    name: "University of Benin",
    code: "UNIBEN",
    state: "Edo",
    city: "Benin City",
    type: "University",
  },
  {
    name: "University of Calabar",
    code: "UNICAL",
    state: "Cross River",
    city: "Calabar",
    type: "University",
  },
  {
    name: "University of Ibadan",
    code: "UI",
    state: "Oyo",
    city: "Ibadan",
    type: "University",
  },
  {
    name: "University of Ilorin",
    code: "UNILORIN",
    state: "Kwara",
    city: "Ilorin",
    type: "University",
  },
  {
    name: "University of Jos",
    code: "UNIJOS",
    state: "Plateau",
    city: "Jos",
    type: "University",
  },
  {
    name: "University of Lagos",
    code: "UNILAG",
    state: "Lagos",
    city: "Akoka",
    type: "University",
  },
  {
    name: "University of Maiduguri",
    code: "UNIMAID",
    state: "Borno",
    city: "Maiduguri",
    type: "University",
  },
  {
    name: "University of Nigeria, Nsukka",
    code: "UNN",
    state: "Enugu",
    city: "Nsukka",
    type: "University",
  },
  {
    name: "University of Port Harcourt",
    code: "UNIPORT",
    state: "Rivers",
    city: "Port Harcourt",
    type: "University",
  },
  {
    name: "University of Uyo",
    code: "UNIUYO",
    state: "Akwa Ibom",
    city: "Uyo",
    type: "University",
  },
  {
    name: "Usmanu Danfodiyo University",
    code: "UDUS",
    state: "Sokoto",
    city: "Sokoto",
    type: "University",
  },
  // State Universities
  {
    name: "Abdulkadir Kure University",
    code: "AKUM",
    state: "Niger",
    city: "Minna",
    type: "University",
  },
  {
    name: "Abia State University",
    code: "ABSU",
    state: "Abia",
    city: "Uturu",
    type: "University",
  },
  {
    name: "Adamawa State University",
    code: "ADSU",
    state: "Adamawa",
    city: "Mubi",
    type: "University",
  },
  {
    name: "Adekunle Ajasin University",
    code: "AAUA",
    state: "Ondo",
    city: "Akungba-Akoko",
    type: "University",
  },
  {
    name: "Akwa Ibom State University",
    code: "AKSU",
    state: "Akwa Ibom",
    city: "Uyo",
    type: "University",
  },
  {
    name: "Aliko Dangote University of Science and Technology",
    code: "ADUSTECH",
    state: "Kano",
    city: "Wudil",
    type: "University",
  },
  {
    name: "Ambrose Alli University",
    code: "AAU",
    state: "Edo",
    city: "Ekpoma",
    type: "University",
  },
  {
    name: "Bauchi State University",
    code: "BASUG",
    state: "Bauchi",
    city: "Gadau",
    type: "University",
  },
  {
    name: "Bayelsa Medical University",
    code: "BMU",
    state: "Bayelsa",
    city: "Yenagoa",
    type: "University",
  },
  {
    name: "Benue State University",
    code: "BSU",
    state: "Benue",
    city: "Makurdi",
    type: "University",
  },
  {
    name: "Borno State University",
    code: "BOSU",
    state: "Borno",
    city: "Maiduguri",
    type: "University",
  },
  {
    name: "Bukar Abba Ibrahim University",
    code: "YSU",
    state: "Yobe",
    city: "Damaturu",
    type: "University",
  },
  {
    name: "Chukwuemeka Odumegwu Ojukwu University",
    code: "ANSU",
    state: "Anambra",
    city: "Uli",
    type: "University",
  },
  {
    name: "University of Cross River State",
    code: "UNICROSS",
    state: "Cross River",
    city: "Calabar",
    type: "University",
  },
  {
    name: "Delta State University, Abraka",
    code: "DELSU",
    state: "Delta",
    city: "Abraka",
    type: "University",
  },
  {
    name: "Delta State University of Science and Technology",
    code: "DSPZ",
    state: "Delta",
    city: "Ozoro",
    type: "University",
  },
  {
    name: "Dennis Osadebay University",
    code: "DOU",
    state: "Delta",
    city: "Asaba",
    type: "University",
  },
  {
    name: "Ebonyi State University",
    code: "EBSU",
    state: "Ebonyi",
    city: "Abakaliki",
    type: "University",
  },
  {
    name: "Edo State University, Uzairue",
    code: "EDSU",
    state: "Edo",
    city: "Iyamho",
    type: "University",
  },
  {
    name: "Ekiti State University",
    code: "EKSU",
    state: "Ekiti",
    city: "Ado Ekiti",
    type: "University",
  },
  {
    name: "Enugu State University of Science and Technology",
    code: "ESUT",
    state: "Enugu",
    city: "Enugu",
    type: "University",
  },
  {
    name: "Gombe State University",
    code: "GSU",
    state: "Gombe",
    city: "Gombe",
    type: "University",
  },
  {
    name: "Gombe State University of Science and Technology",
    code: "GSUST",
    state: "Gombe",
    city: "Kumo",
    type: "University",
  },
  {
    name: "Ibrahim Badamasi Babangida University",
    code: "IBBUL",
    state: "Niger",
    city: "Lapai",
    type: "University",
  },
  {
    name: "Ignatius Ajuru University of Education",
    code: "IAUE",
    state: "Rivers",
    city: "Port Harcourt",
    type: "University",
  },
  {
    name: "Imo State University",
    code: "IMSU",
    state: "Imo",
    city: "Owerri",
    type: "University",
  },
  {
    name: "Kaduna State University",
    code: "KASU",
    state: "Kaduna",
    city: "Kaduna",
    type: "University",
  },
  {
    name: "Kebbi State University of Science and Technology",
    code: "KSUSTA",
    state: "Kebbi",
    city: "Aliero",
    type: "University",
  },
  {
    name: "Prince Abubakar Audu University",
    code: "PAAU",
    state: "Kogi",
    city: "Anyigba",
    type: "University",
  },
  {
    name: "Kwara State University",
    code: "KWASU",
    state: "Kwara",
    city: "Malete",
    type: "University",
  },
  {
    name: "Ladoke Akintola University of Technology",
    code: "LAUTECH",
    state: "Oyo",
    city: "Ogbomoso",
    type: "University",
  },
  {
    name: "Lagos State University",
    code: "LASU",
    state: "Lagos",
    city: "Ojo",
    type: "University",
  },
  {
    name: "Lagos State University of Education",
    code: "LASUED",
    state: "Lagos",
    city: "Ijanikin",
    type: "University",
  },
  {
    name: "Lagos State University of Science and Technology",
    code: "LASUST",
    state: "Lagos",
    city: "Ikorodu",
    type: "University",
  },
  {
    name: "Nasarawa State University",
    code: "NSUK",
    state: "Nasarawa",
    city: "Keffi",
    type: "University",
  },
  {
    name: "Niger Delta University",
    code: "NDU",
    state: "Bayelsa",
    city: "Amassoma",
    type: "University",
  },
  {
    name: "Olabisi Onabanjo University",
    code: "OOU",
    state: "Ogun",
    city: "Ago-Iwoye",
    type: "University",
  },
  {
    name: "Olusegun Agagu University of Science and Technology",
    code: "OAUST",
    state: "Ondo",
    city: "Okitipupa",
    type: "University",
  },
  {
    name: "Osun State University",
    code: "UNIOSUN",
    state: "Osun",
    city: "Osogbo",
    type: "University",
  },
  {
    name: "Plateau State University",
    code: "PLASU",
    state: "Plateau",
    city: "Bokkos",
    type: "University",
  },
  {
    name: "Rivers State University",
    code: "RIVSU",
    state: "Rivers",
    city: "Port Harcourt",
    type: "University",
  },
  {
    name: "Sule Lamido University",
    code: "SLU",
    state: "Jigawa",
    city: "Kafin-Hausa",
    type: "University",
  },
  {
    name: "Tai Solarin University of Education",
    code: "TASUED",
    state: "Ogun",
    city: "Ijebu Ode",
    type: "University",
  },
  {
    name: "Taraba State University",
    code: "TSU",
    state: "Taraba",
    city: "Jalingo",
    type: "University",
  },
  {
    name: "Umaru Musa Yar'adua University",
    code: "UMYU",
    state: "Katsina",
    city: "Katsina",
    type: "University",
  },
  {
    name: "Sokoto State University",
    code: "SSU",
    state: "Sokoto",
    city: "Sokoto",
    type: "University",
  },
  {
    name: "University of Delta",
    code: "UNIDEL",
    state: "Delta",
    city: "Agbor",
    type: "University",
  },
  {
    name: "Yusuf Maitama Sule University Kano",
    code: "YUMSUK",
    state: "Kano",
    city: "Kano",
    type: "University",
  },
  {
    name: "Zamfara State University",
    code: "ZSU",
    state: "Zamfara",
    city: "Talata Mafara",
    type: "University",
  },
  // Uniformed Universities
  {
    name: "Nigeria Airforce University",
    code: "AFIT",
    state: "Kaduna",
    city: "Kaduna",
    type: "University",
  },
  {
    name: "Nigeria Maritime University",
    code: "NMU",
    state: "Delta",
    city: "Warri",
    type: "University",
  },
  {
    name: "Nigeria Police Academy Wudil",
    code: "POLAC",
    state: "Kano",
    city: "Wudil",
    type: "University",
  },
  {
    name: "Nigerian Army University Biu",
    code: "NUAB",
    state: "Borno",
    city: "Biu",
    type: "University",
  },
  {
    name: "Nigerian Defence Academy",
    code: "NDA",
    state: "Kaduna",
    city: "Kaduna",
    type: "University",
  },
  // Private Universities
  {
    name: "Achievers University",
    code: "AC",
    state: "Ondo",
    city: "Owo",
    type: "University",
  },
  {
    name: "Adeleke University",
    code: "AUE",
    state: "Osun",
    city: "Ede",
    type: "University",
  },
  {
    name: "Afe Babalola University",
    code: "ABUAD",
    state: "Ekiti",
    city: "Ado-Ekiti",
    type: "University",
  },
  {
    name: "African University of Science and Technology",
    code: "AUST",
    state: "Federal Capital Territory",
    city: "Abuja",
    type: "University",
  },
  {
    name: "Ahman Pategi University",
    code: "APU",
    state: "Kwara",
    city: "Pategi",
    type: "University",
  },
  {
    name: "Ajayi Crowther University",
    code: "ACU",
    state: "Oyo",
    city: "Oyo",
    type: "University",
  },
  {
    name: "Al-Ansar University Maiduguri",
    code: "AUM",
    state: "Borno",
    city: "Maiduguri",
    type: "University",
  },
  {
    name: "Al-Hikmah University",
    code: "AHU",
    state: "Kwara",
    city: "Ilorin",
    type: "University",
  },
  {
    name: "Al-Qalam University",
    code: "AUK",
    state: "Katsina",
    city: "Katsina",
    type: "University",
  },
  {
    name: "American University of Nigeria",
    code: "AUN",
    state: "Adamawa",
    city: "Yola",
    type: "University",
  },
  {
    name: "Anchor University",
    code: "",
    state: "Lagos",
    city: "Ayobo",
    type: "University",
  },
  {
    name: "Arthur Jarvis University",
    code: "AJU",
    state: "Cross River",
    city: "Akpabuyo",
    type: "University",
  },
  {
    name: "Ave Maria University",
    code: "AMU",
    state: "Nasarawa",
    city: "Piyanko",
    type: "University",
  },
  {
    name: "Babcock University",
    code: "BU",
    state: "Ogun",
    city: "Ilishan-Remo",
    type: "University",
  },
  {
    name: "Baze University",
    code: "BAZE",
    state: "Federal Capital Territory",
    city: "Abuja",
    type: "University",
  },
  {
    name: "Bells University of Technology",
    code: "BUT",
    state: "Ogun",
    city: "Ota",
    type: "University",
  },
  {
    name: "Benson Idahosa University",
    code: "BIU",
    state: "Edo",
    city: "Benin City",
    type: "University",
  },
  {
    name: "Bowen University",
    code: "BU",
    state: "Osun",
    city: "Iwo",
    type: "University",
  },
  {
    name: "Bingham University",
    code: "BHU",
    state: "Nasarawa",
    city: "Karu",
    type: "University",
  },
  {
    name: "Caleb University",
    code: "CUl",
    state: "Lagos",
    city: "Ikorodu",
    type: "University",
  },
  {
    name: "Caritas University",
    code: "",
    state: "Enugu",
    city: "Enugu",
    type: "University",
  },
  {
    name: "CETEP City University",
    code: "",
    state: "Lagos",
    city: "Yaba",
    type: "University",
  },
  {
    name: "Chrisland University",
    code: "CLU",
    state: "Ogun",
    city: "Abeokuta",
    type: "University",
  },
  {
    name: "Christopher University",
    code: "",
    state: "Ogun",
    city: "Mowe",
    type: "University",
  },
  {
    name: "Clifford University",
    code: "CLU",
    state: "Abia",
    city: "Owerrinta",
    type: "University",
  },
  {
    name: "Coal City University",
    code: "CCU",
    state: "Enugu",
    city: "Enugu",
    type: "University",
  },
  {
    name: "Covenant University",
    code: "CU",
    state: "Ogun",
    city: "Ota",
    type: "University",
  },
  {
    name: "Crawford University",
    code: "",
    state: "Ogun",
    city: "Igbesa",
    type: "University",
  },
  {
    name: "Crescent University",
    code: "",
    state: "Ogun",
    city: "Abeokuta",
    type: "University",
  },
  {
    name: "Dominican University Ibadan",
    code: "DUI",
    state: "Oyo",
    city: "Ibadan",
    type: "University",
  },
  {
    name: "Edwin Clark University",
    code: "ECU",
    state: "Delta",
    city: "Kiagbodo",
    type: "University",
  },
  {
    name: "Elizade University",
    code: "EU",
    state: "Ondo",
    city: "Ilara-Mokin",
    type: "University",
  },
  {
    name: "Evangel University, Akaeze",
    code: "EUA",
    state: "Ebonyi",
    city: "Akaeze",
    type: "University",
  },
  {
    name: "Fountain University",
    code: "FUO",
    state: "Osun",
    city: "Osogbo",
    type: "University",
  },
  {
    name: "Godfrey Okoye University",
    code: "GOU",
    state: "Enugu",
    city: "Enugu",
    type: "University",
  },
  {
    name: "Greenfield University",
    code: "GFU",
    state: "Kaduna",
    city: "Kaduna",
    type: "University",
  },
  {
    name: "Gregory University",
    code: "GUU",
    state: "Abia",
    city: "Uturu",
    type: "University",
  },
  {
    name: "Hallmark University",
    code: "",
    state: "Ogun",
    city: "Ijebu-Itele",
    type: "University",
  },
  {
    name: "Hezekiah University",
    code: "",
    state: "Imo",
    city: "Umudi",
    type: "University",
  },
  {
    name: "Igbinedion University",
    code: "IUO",
    state: "Edo",
    city: "Okada",
    type: "University",
  },
  {
    name: "Joseph Ayo Babalola University",
    code: "JABU",
    state: "Osun",
    city: "Ikeji-Arakeji",
    type: "University",
  },
  {
    name: "Khadija University",
    code: "KUM",
    state: "Jigawa",
    city: "Majia",
    type: "University",
  },
  {
    name: "Kings University",
    code: "KU",
    state: "Osun",
    city: "Odeomu",
    type: "University",
  },
  {
    name: "Koladaisi University",
    code: "KU",
    state: "Oyo",
    city: "Ibadan",
    type: "University",
  },
  {
    name: "Kwararafa University",
    code: "",
    state: "Taraba",
    city: "Wukari",
    type: "University",
  },
  {
    name: "Landmark University",
    code: "LU",
    state: "Kwara",
    city: "Omu-Aran",
    type: "University",
  },
  {
    name: "Lead City University",
    code: "LCU",
    state: "Oyo",
    city: "Ibadan",
    type: "University",
  },
  {
    name: "Madonna University",
    code: "",
    state: "Rivers",
    city: "Elele",
    type: "University",
  },
  {
    name: "McPherson University",
    code: "MCU",
    state: "Ogun",
    city: "Seriki-Setayo",
    type: "University",
  },
  {
    name: "Mewar University",
    code: "",
    state: "Nasarawa",
    city: "Masaka",
    type: "University",
  },
  {
    name: "Michael and Cecilia Ibru University",
    code: "MCIU",
    state: "Delta",
    city: "Agbara-Otor",
    type: "University",
  },
  {
    name: "Mountain Top University",
    code: "MTU",
    state: "Ogun",
    city: "Makogi Oba",
    type: "University",
  },
  {
    name: "Mudiame University",
    code: "",
    state: "Edo",
    city: "Irrua",
    type: "University",
  },
  {
    name: "Nile University of Nigeria",
    code: "NUN",
    state: "Federal Capital Territory",
    city: "Abuja",
    type: "University",
  },
  {
    name: "Nok University Kachia",
    code: "NUK",
    state: "Kaduna",
    city: "Kachia",
    type: "University",
  },
  {
    name: "Novena University",
    code: "",
    state: "Delta",
    city: "Ogume",
    type: "University",
  },
  {
    name: "Obong University",
    code: "",
    state: "Akwa Ibom",
    city: "Obong Ntak",
    type: "University",
  },
  {
    name: "Oduduwa University",
    code: "OUI",
    state: "Osun",
    city: "Ipetumodu",
    type: "University",
  },
  {
    name: "PAMO University of Medical Sciences",
    code: "",
    state: "Rivers",
    city: "Port Harcourt",
    type: "University",
  },
  {
    name: "Pan-Atlantic University",
    code: "PAU",
    state: "Lagos",
    city: "Lekki",
    type: "University",
  },
  {
    name: "Paul University",
    code: "",
    state: "Anambra",
    city: "Awka",
    type: "University",
  },
  {
    name: "Peaceland University",
    code: "PUE",
    state: "Enugu",
    city: "Enugu",
    type: "University",
  },
  {
    name: "Precious Cornerstone University",
    code: "PCU",
    state: "Oyo",
    city: "Ibadan",
    type: "University",
  },
  {
    name: "Redeemer's University Nigeria",
    code: "RUN",
    state: "Osun",
    city: "Ede",
    type: "University",
  },
  {
    name: "Renaissance University",
    code: "",
    state: "Enugu",
    city: "Ugbawka",
    type: "University",
  },
  {
    name: "Rhema University",
    code: "",
    state: "Abia",
    city: "Aba",
    type: "University",
  },
  {
    name: "Ritman University",
    code: "",
    state: "Akwa Ibom",
    city: "Ikot Ekpene",
    type: "University",
  },
  {
    name: "Salem University",
    code: "",
    state: "Kogi",
    city: "Lokoja",
    type: "University",
  },
  {
    name: "Sam Maris University",
    code: "SMU",
    state: "Ondo",
    city: "Supare",
    type: "University",
  },
  {
    name: "Samuel Adegboyega University",
    code: "SAU",
    state: "Edo",
    city: "Ogwa",
    type: "University",
  },
  {
    name: "Skyline University",
    code: "SUN",
    state: "Kano",
    city: "Kano",
    type: "University",
  },
  {
    name: "Summit University",
    code: "",
    state: "Kwara",
    city: "Offa",
    type: "University",
  },
  {
    name: "Veritas University (Catholic University of Nigeria) Abuja",
    code: "VUNA",
    state: "Federal Capital Territory",
    city: "Bwari",
    type: "University",
  },
  {
    name: "Wesley University",
    code: "WUO",
    state: "Ondo",
    city: "Ondo",
    type: "University",
  },
  {
    name: "Western Delta University",
    code: "WDU",
    state: "Delta",
    city: "Oghara",
    type: "University",
  },
  {
    name: "Westland University",
    code: "WUI",
    state: "Osun",
    city: "Iwo",
    type: "University",
  },
  {
    name: "University of Mkar",
    code: "",
    state: "Benue",
    city: "Mkar",
    type: "University",
  },
  {
    name: "James Hope University, Lagos",
    code: "JHU",
    state: "Lagos",
    city: "Lekki",
    type: "University",
  },
  // Colleges of Education - Federal
  {
    name: "Federal College of Education (Special), Oyo",
    code: "",
    state: "Oyo",
    city: "Oyo",
    type: "College of Education",
  },
  {
    name: "Adeyemi College of Education",
    code: "",
    state: "Ondo",
    city: "Ondo",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Iwo",
    code: "",
    state: "Osun",
    city: "Iwo",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Asaba",
    code: "",
    state: "Delta",
    city: "Asaba",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Abeokuta",
    code: "",
    state: "Ogun",
    city: "Abeokuta",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Kano",
    code: "",
    state: "Kano",
    city: "Kano",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Eha-Amufu",
    code: "",
    state: "Enugu",
    city: "Eha-Amufu",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Okene",
    code: "",
    state: "Kogi",
    city: "Okene",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Gombe",
    code: "",
    state: "Gombe",
    city: "Gombe",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Omoku",
    code: "",
    state: "Rivers",
    city: "Omoku",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Kontagora",
    code: "",
    state: "Niger",
    city: "Kontagora",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Zaria",
    code: "",
    state: "Kaduna",
    city: "Zaria",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Pankshin",
    code: "",
    state: "Plateau",
    city: "Pankshin",
    type: "College of Education",
  },
  {
    name: "Alvan Ikoku Federal College of Education",
    code: "",
    state: "Imo",
    city: "Owerri",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Yola",
    code: "",
    state: "Adamawa",
    city: "Yola",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Potiskum",
    code: "",
    state: "Yobe",
    city: "Potiskum",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Gusau",
    code: "",
    state: "Zamfara",
    city: "Gusau",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Akoka",
    code: "",
    state: "Lagos",
    city: "Akoka",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Katsina",
    code: "",
    state: "Katsina",
    city: "Katsina",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Bichi",
    code: "",
    state: "Kano",
    city: "Bichi",
    type: "College of Education",
  },
  {
    name: "Federal College of Education, Obudu",
    code: "",
    state: "Cross River",
    city: "Obudu",
    type: "College of Education",
  },
  {
    name: "Federal College of Education (Technical), Umunze",
    code: "",
    state: "Anambra",
    city: "Umunze",
    type: "College of Education",
  },
  // Colleges of Education - Private
  {
    name: "Piaget College of Education",
    code: "",
    state: "Ogun",
    city: "Abeokuta",
    type: "College of Education",
  },
  {
    name: "St. Augustine College of Education",
    code: "",
    state: "Lagos",
    city: "Akoka",
    type: "College of Education",
  },
  {
    name: "Our Saviour Institute of Science and Technology",
    code: "",
    state: "Enugu",
    city: "Enugu",
    type: "College of Education",
  },
  {
    name: "Delar College of Education",
    code: "",
    state: "Oyo",
    city: "Ibadan",
    type: "College of Education",
  },
  {
    name: "Yewa Central College of Education",
    code: "",
    state: "Ogun",
    city: "Ayetoro",
    type: "College of Education",
  },
  {
    name: "Institute of Ecumenical Education",
    code: "",
    state: "Enugu",
    city: "Enugu",
    type: "College of Education",
  },
  {
    name: "Ansar-Ud-Deen College of Education",
    code: "",
    state: "Lagos",
    city: "Isolo",
    type: "College of Education",
  },
  {
    name: "African Thinkers Community of Inquiry College of Education",
    code: "",
    state: "Enugu",
    city: "Enugu",
    type: "College of Education",
  },
  {
    name: "City College of Education, Mararaba",
    code: "",
    state: "Nasarawa",
    city: "Mararaba",
    type: "College of Education",
  },
  {
    name: "Muftau Olanihun College of Education",
    code: "",
    state: "Oyo",
    city: "Ibadan",
    type: "College of Education",
  },
  {
    name: "Havard Wilson College of Education",
    code: "",
    state: "Abia",
    city: "Aba",
    type: "College of Education",
  },
  {
    name: "College of Education Ilemona",
    code: "",
    state: "Kwara",
    city: "Ilemona",
    type: "College of Education",
  },
  {
    name: "Nana Aishat Memorial College of Education",
    code: "",
    state: "Kwara",
    city: "Ilorin",
    type: "College of Education",
  },
  {
    name: "AJETUNMOBI College of Education Irra",
    code: "",
    state: "Kwara",
    city: "Irra",
    type: "College of Education",
  },
  // Polytechnics - Federal
  {
    name: "Federal Polytechnic, Mubi",
    code: "",
    state: "Adamawa",
    city: "Mubi",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Oko",
    code: "",
    state: "Anambra",
    city: "Oko",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Bauchi",
    code: "",
    state: "Bauchi",
    city: "Bauchi",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic Ekowe",
    code: "",
    state: "Bayelsa",
    city: "Ekowe",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic Monguno",
    code: "",
    state: "Borno",
    city: "Monguno",
    type: "Polytechnic",
  },
  {
    name: "Akanu Ibiam Federal Polytechnic",
    code: "",
    state: "Ebonyi",
    city: "Unwana",
    type: "Polytechnic",
  },
  {
    name: "Auchi Polytechnic",
    code: "",
    state: "Edo",
    city: "Auchi",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Ado-Ekiti",
    code: "",
    state: "Ekiti",
    city: "Ado-Ekiti",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Nekede",
    code: "",
    state: "Imo",
    city: "Nekede",
    type: "Polytechnic",
  },
  {
    name: "Hussaini Adamu Federal Polytechnic",
    code: "",
    state: "Jigawa",
    city: "Kazaure",
    type: "Polytechnic",
  },
  {
    name: "Kaduna Polytechnic",
    code: "",
    state: "Kaduna",
    city: "Kaduna",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Birnin-Kebbi",
    code: "",
    state: "Kebbi",
    city: "Birnin-Kebbi",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Idah",
    code: "",
    state: "Kogi",
    city: "Idah",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Offa",
    code: "",
    state: "Kwara",
    city: "Offa",
    type: "Polytechnic",
  },
  {
    name: "Yaba College of Technology",
    code: "",
    state: "Lagos",
    city: "Yaba",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic Nasarawa",
    code: "",
    state: "Nasarawa",
    city: "Nasarawa",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Bida",
    code: "",
    state: "Niger",
    city: "Bida",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Ilaro",
    code: "",
    state: "Ogun",
    city: "Ilaro",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Ede",
    code: "",
    state: "Osun",
    city: "Ede",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic Ayede",
    code: "",
    state: "Oyo",
    city: "Ayede",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic Damaturu",
    code: "",
    state: "Yobe",
    city: "Damaturu",
    type: "Polytechnic",
  },
  {
    name: "Federal Polytechnic, Kauran Namoda",
    code: "",
    state: "Zamfara",
    city: "Kaura-Namoda",
    type: "Polytechnic",
  },
  // Polytechnics - State
  {
    name: "Abia State Polytechnic",
    code: "",
    state: "Abia",
    city: "Aba",
    type: "Polytechnic",
  },
  {
    name: "Adamawa State Polytechnic",
    code: "",
    state: "Adamawa",
    city: "Yola",
    type: "Polytechnic",
  },
  {
    name: "Akwa Ibom State Polytechnic",
    code: "",
    state: "Akwa Ibom",
    city: "Ikot Ekpene",
    type: "Polytechnic",
  },
  {
    name: "Ekwenugo Okeke Polytechnic",
    code: "",
    state: "Anambra",
    city: "Uli",
    type: "Polytechnic",
  },
  {
    name: "Anambra State Polytechnic",
    code: "",
    state: "Anambra",
    city: "Mgbakwu",
    type: "Polytechnic",
  },
  {
    name: "Abubakar Tatari Ali Polytechnic",
    code: "",
    state: "Bauchi",
    city: "Bauchi",
    type: "Polytechnic",
  },
  {
    name: "Benue State Polytechnic",
    code: "",
    state: "Benue",
    city: "Ugbokolo",
    type: "Polytechnic",
  },
  {
    name: "Ramat Polytechnic",
    code: "",
    state: "Borno",
    city: "Maiduguri",
    type: "Polytechnic",
  },
  {
    name: "Delta State Polytechnic",
    code: "",
    state: "Delta",
    city: "Otefe-Oghara",
    type: "Polytechnic",
  },
  {
    name: "Edo State Polytechnic",
    code: "",
    state: "Edo",
    city: "Usen",
    type: "Polytechnic",
  },
  {
    name: "Enugu State Polytechnic",
    code: "",
    state: "Enugu",
    city: "Iwollo",
    type: "Polytechnic",
  },
  {
    name: "Institute of Management Technology",
    code: "",
    state: "Enugu",
    city: "Enugu",
    type: "Polytechnic",
  },
  {
    name: "Imo State Polytechnic",
    code: "",
    state: "Imo",
    city: "Umuagwo",
    type: "Polytechnic",
  },
  {
    name: "Nuhu Bamalli Polytechnic",
    code: "",
    state: "Kaduna",
    city: "Zaria",
    type: "Polytechnic",
  },
  {
    name: "Kano State Polytechnic",
    code: "",
    state: "Kano",
    city: "Kano",
    type: "Polytechnic",
  },
  {
    name: "Hassan Usman Katsina Polytechnic",
    code: "",
    state: "Katsina",
    city: "Katsina",
    type: "Polytechnic",
  },
  {
    name: "Kebbi State Polytechnic",
    code: "",
    state: "Kebbi",
    city: "Dakingari",
    type: "Polytechnic",
  },
  {
    name: "Kogi State Polytechnic",
    code: "",
    state: "Kogi",
    city: "Lokoja",
    type: "Polytechnic",
  },
  {
    name: "Kwara State Polytechnic",
    code: "",
    state: "Kwara",
    city: "Ilorin",
    type: "Polytechnic",
  },
  {
    name: "Lagos State Polytechnic",
    code: "",
    state: "Lagos",
    city: "Ikorodu",
    type: "Polytechnic",
  },
  {
    name: "Nasarawa State Polytechnic",
    code: "",
    state: "Nasarawa",
    city: "Lafia",
    type: "Polytechnic",
  },
  {
    name: "Niger State Polytechnic",
    code: "",
    state: "Niger",
    city: "Zungeru",
    type: "Polytechnic",
  },
  {
    name: "Abraham Adesanya Polytechnic",
    code: "",
    state: "Ogun",
    city: "Ijebu-Igbo",
    type: "Polytechnic",
  },
  {
    name: "Gateway Polytechnic",
    code: "",
    state: "Ogun",
    city: "Saapade",
    type: "Polytechnic",
  },
  {
    name: "Moshood Abiola Polytechnic",
    code: "",
    state: "Ogun",
    city: "Abeokuta",
    type: "Polytechnic",
  },
  {
    name: "Rufus Giwa Polytechnic",
    code: "",
    state: "Ondo",
    city: "Owo",
    type: "Polytechnic",
  },
  {
    name: "Osun State Polytechnic",
    code: "",
    state: "Osun",
    city: "Iree",
    type: "Polytechnic",
  },
  {
    name: "The Polytechnic, Ibadan",
    code: "",
    state: "Oyo",
    city: "Ibadan",
    type: "Polytechnic",
  },
  {
    name: "Plateau State Polytechnic",
    code: "",
    state: "Plateau",
    city: "Barkin-Ladi",
    type: "Polytechnic",
  },
  {
    name: "Rivers State Polytechnic",
    code: "",
    state: "Rivers",
    city: "Bori",
    type: "Polytechnic",
  },
  {
    name: "Port Harcourt Polytechnic",
    code: "",
    state: "Rivers",
    city: "Port Harcourt",
    type: "Polytechnic",
  },
  {
    name: "Mai Idris Alooma Polytechnic",
    code: "",
    state: "Yobe",
    city: "Geidam",
    type: "Polytechnic",
  },
  {
    name: "Abdul Gusau Polytechnic",
    code: "",
    state: "Zamfara",
    city: "Talata Mafara",
    type: "Polytechnic",
  },
  // Polytechnics - Private
  {
    name: "Dorben Polytechnic",
    code: "",
    state: "Abuja",
    city: "Abuja",
    type: "Polytechnic",
  },
  {
    name: "Citi Polytechnic",
    code: "",
    state: "Abuja",
    city: "Abuja",
    type: "Polytechnic",
  },
  {
    name: "Foundation College of Technology",
    code: "",
    state: "Akwa Ibom",
    city: "Ikot Ekpene",
    type: "Polytechnic",
  },
  {
    name: "Heritage Polytechnic",
    code: "",
    state: "Akwa Ibom",
    city: "Eket",
    type: "Polytechnic",
  },
  {
    name: "Southern Atlantic Polytechnic",
    code: "",
    state: "Akwa Ibom",
    city: "Uyo",
    type: "Polytechnic",
  },
  {
    name: "The UA College of Science and Technology",
    code: "",
    state: "Anambra",
    city: "Anambra",
    type: "Polytechnic",
  },
  {
    name: "Kings Polytechnic",
    code: "",
    state: "Edo",
    city: "Ubiaja",
    type: "Polytechnic",
  },
  {
    name: "Shaka Polytechnic",
    code: "",
    state: "Edo",
    city: "Benin City",
    type: "Polytechnic",
  },
  {
    name: "Temple Gate Polytechnic",
    code: "",
    state: "Abia",
    city: "Aba",
    type: "Polytechnic",
  },
  {
    name: "Coastal Polytechnic",
    code: "",
    state: "Lagos",
    city: "Apapa",
    type: "Polytechnic",
  },
  {
    name: "Grace Polytechnic",
    code: "",
    state: "Lagos",
    city: "Lagos",
    type: "Polytechnic",
  },
  {
    name: "Lagos City Polytechnic",
    code: "",
    state: "Lagos",
    city: "Lagos",
    type: "Polytechnic",
  },
  {
    name: "Ronik Polytechnic",
    code: "",
    state: "Lagos",
    city: "Lagos",
    type: "Polytechnic",
  },
  {
    name: "Wolex Polytechnic",
    code: "",
    state: "Lagos",
    city: "Lagos",
    type: "Polytechnic",
  },
  {
    name: "Allover Central Polytechnic",
    code: "",
    state: "Ogun",
    city: "Sango-Ota",
    type: "Polytechnic",
  },
  {
    name: "Igbajo Polytechnic",
    code: "",
    state: "Osun",
    city: "Igbajo",
    type: "Polytechnic",
  },
  {
    name: "Iwo City Polytechnic",
    code: "",
    state: "Osun",
    city: "Iwo",
    type: "Polytechnic",
  },
  {
    name: "Polytechnic Ile-Ife",
    code: "",
    state: "Osun",
    city: "Ile-Ife",
    type: "Polytechnic",
  },
  {
    name: "Interlink Polytechnic",
    code: "",
    state: "Osun",
    city: "Ijebu-Jesa",
    type: "Polytechnic",
  },
  {
    name: "Villanova Polytechnic",
    code: "",
    state: "Osun",
    city: "Imesi Ile",
    type: "Polytechnic",
  },
  {
    name: "Novelty Polytechnic",
    code: "",
    state: "Oyo",
    city: "Kishi",
    type: "Polytechnic",
  },
  {
    name: "Tower Polytechnic",
    code: "",
    state: "Oyo",
    city: "Ibadan",
    type: "Polytechnic",
  },
  {
    name: "Eastern Polytechnic",
    code: "",
    state: "Rivers",
    city: "Port Harcourt",
    type: "Polytechnic",
  },
];

async function seedUniversities() {
  try {
    await SeederDataSource.initialize();

    const institutionRepository = SeederDataSource.getRepository(Institution);

    for (const inst of institutions) {
      const existing = await institutionRepository.findOne({
        where: { name: inst.name },
      });
      if (!existing) {
        const institution = institutionRepository.create(inst);
        await institutionRepository.save(institution);
        console.log(`Inserted: ${inst.name}`);
      } else {
        console.log(`Skipped: ${inst.name} (already exists)`);
      }
    }

    console.log("Seeding completed");
  } catch (error) {
    console.error("Error seeding institutions:", error);
  } finally {
    await SeederDataSource.destroy();
  }
}

seedUniversities();
